// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCurrentRun() {
  return window['go']['main']['App']['CancelCurrentRun']();
}

export function CreateNewSession() {
  return window['go']['main']['App']['CreateNewSession']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetChatHistory() {
  return window['go']['main']['App']['GetChatHistory']();
}

export function GetContextUsage(arg1) {
  return window['go']['main']['App']['GetContextUsage'](arg1);
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSupportedModels() {
  return window['go']['main']['App']['GetSupportedModels']();
}

export function ListSessions(arg1) {
  return window['go']['main']['App']['ListSessions'](arg1);
}

export function OpenInFileManager(arg1) {
  return window['go']['main']['App']['OpenInFileManager'](arg1);
}

export function SendPrompt(arg1) {
  return window['go']['main']['App']['SendPrompt'](arg1);
}

export function SetApiKey(arg1) {
  return window['go']['main']['App']['SetApiKey'](arg1);
}

export function SetBaseURL(arg1) {
  return window['go']['main']['App']['SetBaseURL'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetOrchestrateParallel(arg1) {
  return window['go']['main']['App']['SetOrchestrateParallel'](arg1);
}

export function SetPermissions(arg1) {
  return window['go']['main']['App']['SetPermissions'](arg1);
}

export function SetSudoPassword(arg1) {
  return window['go']['main']['App']['SetSudoPassword'](arg1);
}

export function SwitchSession(arg1) {
  return window['go']['main']['App']['SwitchSession'](arg1);
}
