// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {app} from '../models';

export function CancelCurrentRun():Promise<boolean>;

export function CreateNewSession():Promise<string>;

export function DeleteSession(arg1:string):Promise<string>;

export function GetChatHistory():Promise<Array<main.DesktopChatMessage>>;

export function GetContextUsage(arg1:string):Promise<app.ContextUsage>;

export function GetRecentLogs(arg1:number):Promise<string>;

export function GetStatus():Promise<main.DesktopRunStatus>;

export function GetSupportedModels():Promise<Array<string>>;

export function ListSessions(arg1:number):Promise<Array<main.DesktopSessionCard>>;

export function OpenInFileManager(arg1:string):Promise<string>;

export function SendPrompt(arg1:string):Promise<string>;

export function SetApiKey(arg1:string):Promise<string>;

export function SetBaseURL(arg1:string):Promise<string>;

export function SetModel(arg1:string):Promise<string>;

export function SetOrchestrateParallel(arg1:number):Promise<string>;

export function SetPermissions(arg1:string):Promise<string>;

export function SetSudoPassword(arg1:string):Promise<string>;

export function SwitchSession(arg1:string):Promise<Array<main.DesktopChatMessage>>;
